name: "Build with Nix and publish to Cloudflare pages"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: |
        mkdir -p output
        cp -r result output/
        cp *.{html,js,css} output/
        echo "/*" > output/_headers
        echo "  Cross-Origin-Opener-Policy: same-origin" >> output/_headers
        echo "  Cross-Origin-Embedder-Policy: require-corp" >> output/_headers
    - uses: actions/upload-artifact@v4
      with:
        path: output
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 
        projectName: stm-webusb
        directory: output
